# Generated by Django 4.2.7 on 2023-11-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('district', models.CharField(choices=[('Kottayam', 'Kottayam'), ('Ernakulam', 'Ernakulam'), ('Kollam', 'Kollam'), ('Malappuram', 'Malappuram'), ('Kannur', 'Kannur')], max_length=50)),
                ('branch', models.CharField(choices=[('Alanallur', 'Alanallur'), ('Calicut', 'Calicut'), ('Aluva', 'Aluva'), ('Edapally', 'Edapally'), ('Cannanore', 'Cannanore')], max_length=50)),
                ('account_type', models.CharField(choices=[('Savings Account', 'Savings Account'), ('Current Account', 'Current Account')], max_length=50)),
                ('materials_provided', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
